name: "workflow command"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
         echo "::group::Hello from the workflow"
         echo "::message 1"
         echo "::message 2"
         echo "::endgroup::"
         
